version: '3'

services:
  traefik:
    image: traefik:1.7
    command: --docker
    ports:
      - 80:80
      - 443:443
      -  ${TRAEFIK_MANAGEMENT_HTTP_HOST_PORT}:8080
    networks:
      - webproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.toml:/traefik.toml
      - ./data/acme.json:/acme.json
    labels:
      - traefik.enable=false
    container_name: traefik
    restart: always
networks:
  webproxy:
    external: true
